# Generated by Django 5.1.5 on 2025-02-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_status_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='status',
        ),
    ]
