# Generated by Django 5.1.5 on 2025-02-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_payment_status_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
