# Generated by Django 5.1.5 on 2025-02-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_razorpay_order_id_remove_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
