# Generated by Django 5.1.5 on 2025-02-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvisit',
            name='last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
